[tool.isort]
profile = "black"
src_paths = ["tutorials", "examples"]
include_trailing_comma = true
multi_line_output = 3
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "NUMERIC", "PLOTTING", "BIO", "FIRSTPARTY", "LOCALFOLDER"]
# also contains what we import in notebooks
known_bio = ["scanpy", "squidpy"]
known_numeric = ["numpy", "scipy", "networkx", "sklearn", "pandas"]
known_plotting = ["matplotlib", "seaborn"]
